/* -*- c -*- */
tort_d_mt(block)
tort_d_mt(boolean)
tort_d_mt(caller_info)
tort_d_mt(dynlib)
tort_d_mt(eos)
tort_d_mt(fixnum)
tort_d_mt(gc)
tort_d_mt(io)
tort_d_mt(locative)
tort_d_mt(map)
tort_d_mt(message)
tort_d_mt(method)
tort_d_mt(mtable)
tort_d_mt(nil)
tort_d_mt(object)
tort_d_mt(pair)
tort_d_mt(ptr)
tort_d_mt(runtime)
tort_d_mt(string)
tort_d_mt(symbol)
tort_d_mt(tagged)
tort_d_mt(value)
tort_d_mt(vector)
tort_d_mt(vector_base)
tort_d_mt(word)
/* -*- c -*- */
#undef tort_d_mt
