tort_d_mt(mtable)
tort_d_mt(object)
tort_d_mt(map)
tort_d_mt(string)
tort_d_mt(vector)
tort_d_mt(symbol)
tort_d_mt(method)
tort_d_mt(message)
tort_d_mt(nil)
tort_d_mt(boolean)
tort_d_mt(tagged)
tort_d_mt(io)
tort_d_mt(eos)
#undef tort_d_mt
