#!/usr/bin/perl
use strict;
my %x = ( );
my $i = 0;
while ( <> ) {
  s/(\@p0x[0-9a-f]+)/$x{$1} ||= '@p0x' . (++ $i)/ge;
  s/(\@0x[0-9a-f]+)/$x{$1} ||= '@0x' . (++ $i)/ge;
  s/(\@i([1-9][0-9]*))/'@i' . ('#' x length($2))/ge;
  s/(\@f(([1-9][0-9]*)(\.[0-9]+)?))/'@f' . ('#' x length($3)) . '.?'/ge;
  s/(tort gc stats: .*? = .*?)(\d+)/$1 . ('#' x length($2))/ge;
  print $_;
}
# print "\n\n", keys %x, "\n", values %x, "\n";
exit 0;
