#!/bin/bash
errors=0
tests=0
action="$1"; shift
for f in "$@"
do
  case "$action"
  in
    run|valgrind)
    tests=`expr $tests + 1`
    in=/dev/null
    if [ -f $f.in ] ; then in=$f.in ; fi
    echo "========= test $f.t < $in: "
    case "$action"
    in
      valgrind)
        (TORT_GC=0 valgrind $f.t <$in || echo $?) 2>&1 | t/filter-output
      ;;
      *)
    ($f.t <$in || echo $?) 2>&1 | t/filter-output > $f.out 
    if ! diff -U 10 $f.exp $f.out ; then 
	echo "========== $f.out ==========" 1>&2 
	cat $f.out 
	echo "========== To accept, run: " 1>&2 
	echo "  rm -f $f.exp; make accept-test TEST_FILES=$f;" 
	echo "  # OR make accept-all-test;" 
	errors=`expr $errors + 1` 
	egrep -e ': line .* (Segmentation|Abort)' $f.out && set -x && gdb --args `dirname $f`/.libs/`basename $f`.t
	set +x 2>/dev/null
    fi
      ;;
    esac
    echo "ok"
    ;;
  esac 
done
case "$action"
in
  run)
    echo "DONE: errors/tests $errors/$tests"
  ;;
esac 
exit $errors
