
  tort_nil => nil
  tort_h_mtable(tort_nil) => @map( 
  _inspect => @method(_inspect,@x1),
  clone => @method(clone,@x2)  )

  tort_true => true
  tort_h_mtable(tort_true) => @map( 
  _inspect => @method(_inspect,@x3),
  clone => @method(clone,@x2)  )

  tort_false => false
  tort_h_mtable(tort_false) => @map( 
  _inspect => @method(_inspect,@x3),
  clone => @method(clone,@x2)  )

  tort_eos => @eos(@x4)
  tort_h_mtable(tort_eos) => @map( 
    )

  tort_i(123) => 123
  tort_h_mtable(tort_i(123)) => @map( 
  + => @method(+,@x5),
  / => @method(/,@x6),
  == => @method(==,@x7),
  >= => @method(>=,@x8),
  > => @method(>,@x9),
  ~ => @method(~,@x10),
  <= => @method(<=,@x11),
  << => @method(<<,@x12),
  < => @method(<,@x13),
  % => @method(%,@x14),
  * => @method(*,@x15),
  != => @method(!=,@x16),
  - => @method(-,@x17),
  ! => @method(!,@x18),
  >> => @method(>>,@x19),
  _inspect => @method(_inspect,@x20),
  clone => @method(clone,@x2)  )

  tort_string_new_cstr("cstring") => "cstring"
  tort_h_mtable(tort_string_new_cstr("cstring")) => @map( 
  _dlopen => @method(_dlopen,@x21),
  _inspect => @method(_inspect,@x22),
  get => @method(get,@x23),
  new => @method(new,@x24),
  set => @method(set,@x25)  )

  tort__s(new) => new
  tort_h_mtable(tort__s(new)) => @map( 
  _inspect => @method(_inspect,@x26),
  _version_change => @method(_version_change,@x27),
  clone => @method(clone,@x2)  )

  tort_object_make() => @object(@x28)
  tort_h_mtable(tort_object_make()) => @map( 
  __debugger => @method(__debugger,@x29),
  __message => @method(__message,@x30),
  __register_finalizer => @method(__register_finalizer,@x31),
  _alloc_size => @method(_alloc_size,@x32),
  _inspect => @method(_inspect,@x33),
  _method_not_found => @method(_method_not_found,@x34),
  _mtable => @method(_mtable,@x35),
  _name => @method(_name,@x36),
  clone => @method(clone,@x37),
  identity => @method(identity,@x2),
  __finalize => @method(__finalize,@x2)  )

  _tort => @tort
  tort_h_mtable(_tort) => @map( 
    )

  tort_(root) => @map( 
  nil => nil,
  true => true,
  false => false,
  mtable => @map( 
  boolean => @map( 
  _inspect => @method(_inspect,@x3),
  clone => @method(clone,@x2)  ),
  eos => @map( 
    ),
  io => @map( 
  __create => @method(__create,@x38),
  __finalize => @method(__finalize,@x39),
  __printf => @method(__printf,@x40),
  __printfv => @method(__printfv,@x41),
  __write => @method(__write,@x42),
  _printfv => @method(_printfv,@x43),
  _write => @method(_write,@x44),
  close => @method(close,@x45),
  eof => @method(eof,@x46),
  error => @method(error,@x47),
  flush => @method(flush,@x48),
  open => @method(open,@x49),
  popen => @method(popen,@x50),
  read => @method(read,@x51)  ),
  map => @map( 
  _inspect => @method(_inspect,@x52),
  _load_symtab => @method(_load_symtab,@x53),
  add => @method(add,@x54),
  clone => @method(clone,@x55),
  delete => @method(delete,@x56),
  get => @method(get,@x57),
  get_entry => @method(get_entry,@x58),
  get_entry_by_value => @method(get_entry_by_value,@x59),
  get_entry_cstr => @method(get_entry_cstr,@x60),
  get_entry_string => @method(get_entry_string,@x61),
  get_key => @method(get_key,@x62),
  get_string => @method(get_string,@x63),
  initialize => @method(initialize,@x64),
  set => @method(set,@x65),
  _run_initializers => @method(_run_initializers,@x66),
  _load_methods => @method(_load_methods,@x67)  ),
  message => @map( 
  _inspect => @method(_inspect,@x68),
  backtrace => @method(backtrace,@x69)  ),
  method => @map( 
  _inspect => @method(_inspect,@x70)  ),
  mtable => @map( 
  lookup => @method(lookup,@x71),
  add_method => @method(add_method,@x72),
  allocate => @method(allocate,@x73),
  _allocate => @method(_allocate,@x74),
  _delegate_changed => @method(_delegate_changed,@x75),
  _method_changed => @method(_method_changed,@x76),
  delegate => @method(delegate,@x77),
  set_delegate => @method(set_delegate,@x78)  ),
  nil => @map( 
  _inspect => @method(_inspect,@x1),
  clone => @method(clone,@x2)  ),
  object => @map( 
  __debugger => @method(__debugger,@x29),
  __message => @method(__message,@x30),
  __register_finalizer => @method(__register_finalizer,@x31),
  _alloc_size => @method(_alloc_size,@x32),
  _inspect => @method(_inspect,@x33),
  _method_not_found => @method(_method_not_found,@x34),
  _mtable => @method(_mtable,@x35),
  _name => @method(_name,@x36),
  clone => @method(clone,@x37),
  identity => @method(identity,@x2),
  __finalize => @method(__finalize,@x2)  ),
  pair => @map( 
  _inspect => @method(_inspect,@x79)  ),
  string => @map( 
  _dlopen => @method(_dlopen,@x21),
  _inspect => @method(_inspect,@x22),
  get => @method(get,@x23),
  new => @method(new,@x24),
  set => @method(set,@x25)  ),
  symbol => @map( 
  _inspect => @method(_inspect,@x26),
  _version_change => @method(_version_change,@x27),
  clone => @method(clone,@x2)  ),
  tagged => @map( 
  + => @method(+,@x5),
  / => @method(/,@x6),
  == => @method(==,@x7),
  >= => @method(>=,@x8),
  > => @method(>,@x9),
  ~ => @method(~,@x10),
  <= => @method(<=,@x11),
  << => @method(<<,@x12),
  < => @method(<,@x13),
  % => @method(%,@x14),
  * => @method(*,@x15),
  != => @method(!=,@x16),
  - => @method(-,@x17),
  ! => @method(!,@x18),
  >> => @method(>>,@x19),
  _inspect => @method(_inspect,@x20),
  clone => @method(clone,@x2)  ),
  vector => @map( 
  _inspect => @method(_inspect,@x80),
  each => @method(each,@x81),
  get => @method(get,@x82),
  map => @method(map,@x83),
  new => @method(new,@x84),
  set => @method(set,@x85)  ),
  vector_base => @map( 
  _add => @method(_add,@x86),
  _append => @method(_append,@x87),
  _data => @method(_data,@x88),
  _initialize => @method(_initialize,@x89),
  _ref => @method(_ref,@x90),
  _resize => @method(_resize,@x91),
  alloc_size => @method(alloc_size,@x92),
  append => @method(append,@x93),
  clone => @method(clone,@x94),
  element_size => @method(element_size,@x95),
  size => @method(size,@x96)  )  ),
  stdin => nil,
  stdout => nil,
  stderr => nil,
  core_symtab => @map( 
  _main => 4294970976,
  4294970976 => _main,
  start => 4294970912,
  4294970912 => start  )  )
  tort_h_mtable(tort_(root)) => @map( 
  _inspect => @method(_inspect,@x52),
  _load_symtab => @method(_load_symtab,@x53),
  add => @method(add,@x54),
  clone => @method(clone,@x55),
  delete => @method(delete,@x56),
  get => @method(get,@x57),
  get_entry => @method(get_entry,@x58),
  get_entry_by_value => @method(get_entry_by_value,@x59),
  get_entry_cstr => @method(get_entry_cstr,@x60),
  get_entry_string => @method(get_entry_string,@x61),
  get_key => @method(get_key,@x62),
  get_string => @method(get_string,@x63),
  initialize => @method(initialize,@x64),
  set => @method(set,@x65),
  _run_initializers => @method(_run_initializers,@x66),
  _load_methods => @method(_load_methods,@x67)  )

DONE
