
  tort_nil => nil
  tort_h_mtable(tort_nil) => @map( 
  _inspect => @method(_inspect,@x1),
  clone => @method(clone,@x2)  )

  tort_true => true
  tort_h_mtable(tort_true) => @map( 
  _inspect => @method(_inspect,@x3),
  clone => @method(clone,@x2)  )

  tort_false => false
  tort_h_mtable(tort_false) => @map( 
  _inspect => @method(_inspect,@x3),
  clone => @method(clone,@x2)  )

  tort_eos => @eos(@x4)
  tort_h_mtable(tort_eos) => @map( 
    )

  tort_i(123) => 123
  tort_h_mtable(tort_i(123)) => @map( 
  + => @method(+,@x5),
  / => @method(/,@x6),
  == => @method(==,@x7),
  >= => @method(>=,@x8),
  > => @method(>,@x9),
  ~ => @method(~,@x10),
  <= => @method(<=,@x11),
  << => @method(<<,@x12),
  < => @method(<,@x13),
  % => @method(%,@x14),
  * => @method(*,@x15),
  != => @method(!=,@x16),
  - => @method(-,@x17),
  ! => @method(!,@x18),
  >> => @method(>>,@x19),
  _inspect => @method(_inspect,@x20),
  clone => @method(clone,@x2)  )

  tort_string_new_cstr("cstring") => "cstring"
  tort_h_mtable(tort_string_new_cstr("cstring")) => @map( 
  _dlopen => @method(_dlopen,@x21),
  _inspect => @method(_inspect,@x22),
  get => @method(get,@x23),
  new => @method(new,@x24),
  set => @method(set,@x25)  )

  tort__s(new) => new
  tort_h_mtable(tort__s(new)) => @map( 
  _inspect => @method(_inspect,@x26),
  clone => @method(clone,@x2)  )

  tort_object_make() => @object(@x27)
  tort_h_mtable(tort_object_make()) => @map( 
  __debugger => @method(__debugger,@x28),
  __message => @method(__message,@x29),
  __register_finalizer => @method(__register_finalizer,@x30),
  _alloc_size => @method(_alloc_size,@x31),
  _inspect => @method(_inspect,@x32),
  _mtable => @method(_mtable,@x33),
  _name => @method(_name,@x34),
  clone => @method(clone,@x35),
  identity => @method(identity,@x2),
  __finalize => @method(__finalize,@x2)  )

  _tort => @tort
  tort_h_mtable(_tort) => @map( 
    )

  tort_(root) => @map( 
  nil => nil,
  true => true,
  false => false,
  mtable => @map( 
  boolean => @map( 
  _inspect => @method(_inspect,@x3),
  clone => @method(clone,@x2)  ),
  eos => @map( 
    ),
  io => @map( 
  __create => @method(__create,@x36),
  __finalize => @method(__finalize,@x37),
  __printf => @method(__printf,@x38),
  __printfv => @method(__printfv,@x39),
  __write => @method(__write,@x40),
  _printfv => @method(_printfv,@x41),
  _write => @method(_write,@x42),
  close => @method(close,@x43),
  eof => @method(eof,@x44),
  error => @method(error,@x45),
  flush => @method(flush,@x46),
  open => @method(open,@x47),
  popen => @method(popen,@x48),
  read => @method(read,@x49)  ),
  map => @map( 
  _inspect => @method(_inspect,@x50),
  _load_symtab => @method(_load_symtab,@x51),
  add => @method(add,@x52),
  clone => @method(clone,@x53),
  delete => @method(delete,@x54),
  get => @method(get,@x55),
  get_entry => @method(get_entry,@x56),
  get_entry_by_value => @method(get_entry_by_value,@x57),
  get_entry_cstr => @method(get_entry_cstr,@x58),
  get_entry_string => @method(get_entry_string,@x59),
  get_key => @method(get_key,@x60),
  get_string => @method(get_string,@x61),
  initialize => @method(initialize,@x62),
  set => @method(set,@x63),
  _run_initializers => @method(_run_initializers,@x64),
  _load_methods => @method(_load_methods,@x65)  ),
  message => @map( 
  _inspect => @method(_inspect,@x66),
  backtrace => @method(backtrace,@x67)  ),
  method => @map( 
  _inspect => @method(_inspect,@x68)  ),
  mtable => @map( 
  lookup => @method(lookup,@x69),
  add_method => @method(add_method,@x70),
  allocate => @method(allocate,@x71),
  _allocate => @method(_allocate,@x72),
  _delegate_changed => @method(_delegate_changed,@x73),
  _method_changed => @method(_method_changed,@x74),
  delegate => @method(delegate,@x75),
  set_delegate => @method(set_delegate,@x76)  ),
  nil => @map( 
  _inspect => @method(_inspect,@x1),
  clone => @method(clone,@x2)  ),
  object => @map( 
  __debugger => @method(__debugger,@x28),
  __message => @method(__message,@x29),
  __register_finalizer => @method(__register_finalizer,@x30),
  _alloc_size => @method(_alloc_size,@x31),
  _inspect => @method(_inspect,@x32),
  _mtable => @method(_mtable,@x33),
  _name => @method(_name,@x34),
  clone => @method(clone,@x35),
  identity => @method(identity,@x2),
  __finalize => @method(__finalize,@x2)  ),
  string => @map( 
  _dlopen => @method(_dlopen,@x21),
  _inspect => @method(_inspect,@x22),
  get => @method(get,@x23),
  new => @method(new,@x24),
  set => @method(set,@x25)  ),
  symbol => @map( 
  _inspect => @method(_inspect,@x26),
  clone => @method(clone,@x2)  ),
  tagged => @map( 
  + => @method(+,@x5),
  / => @method(/,@x6),
  == => @method(==,@x7),
  >= => @method(>=,@x8),
  > => @method(>,@x9),
  ~ => @method(~,@x10),
  <= => @method(<=,@x11),
  << => @method(<<,@x12),
  < => @method(<,@x13),
  % => @method(%,@x14),
  * => @method(*,@x15),
  != => @method(!=,@x16),
  - => @method(-,@x17),
  ! => @method(!,@x18),
  >> => @method(>>,@x19),
  _inspect => @method(_inspect,@x20),
  clone => @method(clone,@x2)  ),
  vector => @map( 
  _inspect => @method(_inspect,@x77),
  each => @method(each,@x78),
  get => @method(get,@x79),
  map => @method(map,@x80),
  new => @method(new,@x81),
  set => @method(set,@x82)  ),
  vector_base => @map( 
  _add => @method(_add,@x83),
  _append => @method(_append,@x84),
  _data => @method(_data,@x85),
  _initialize => @method(_initialize,@x86),
  _ref => @method(_ref,@x87),
  _resize => @method(_resize,@x88),
  alloc_size => @method(alloc_size,@x89),
  append => @method(append,@x90),
  clone => @method(clone,@x91),
  element_size => @method(element_size,@x92),
  size => @method(size,@x93)  )  ),
  stdin => nil,
  stdout => nil,
  stderr => nil,
  core_symtab => @map( 
  _main => 4294973296,
  4294973296 => _main,
  start => 4294973232,
  4294973232 => start  )  )
  tort_h_mtable(tort_(root)) => @map( 
  _inspect => @method(_inspect,@x50),
  _load_symtab => @method(_load_symtab,@x51),
  add => @method(add,@x52),
  clone => @method(clone,@x53),
  delete => @method(delete,@x54),
  get => @method(get,@x55),
  get_entry => @method(get_entry,@x56),
  get_entry_by_value => @method(get_entry_by_value,@x57),
  get_entry_cstr => @method(get_entry_cstr,@x58),
  get_entry_string => @method(get_entry_string,@x59),
  get_key => @method(get_key,@x60),
  get_string => @method(get_string,@x61),
  initialize => @method(initialize,@x62),
  set => @method(set,@x63),
  _run_initializers => @method(_run_initializers,@x64),
  _load_methods => @method(_load_methods,@x65)  )

DONE
