
  tort_nil => nil
  tort_h_mtable(tort_nil) => @map( 
  __printfsv => @method(nil::__printfsv,@x1),
  _inspect => @method(nil::_inspect,@x2),
  clone => @method(nil::clone,@x3)  )

  tort_true => true
  tort_h_mtable(tort_true) => @map( 
  _inspect => @method(boolean::_inspect,@x4),
  clone => @method(boolean::clone,@x3)  )

  tort_false => false
  tort_h_mtable(tort_false) => @map( 
  _inspect => @method(boolean::_inspect,@x4),
  clone => @method(boolean::clone,@x3)  )

  tort_eos => @eos(@x5)
  tort_h_mtable(tort_eos) => @map( 
    )

  tort_i(123) => 123
  tort_h_mtable(tort_i(123)) => @map( 
  + => @method(tagged::+,@x6),
  & => @method(tagged::&,@x7),
  / => @method(tagged::/,@x8),
  == => @method(tagged::==,@x9),
  >= => @method(tagged::>=,@x10),
  > => @method(tagged::>,@x11),
  ~ => @method(tagged::~,@x12),
  && => @method(tagged::&&,@x13),
  <= => @method(tagged::<=,@x14),
  || => @method(tagged::||,@x15),
  << => @method(tagged::<<,@x16),
  < => @method(tagged::<,@x17),
  % => @method(tagged::%,@x18),
  * => @method(tagged::*,@x19),
  != => @method(tagged::!=,@x20),
  !=G => @method(tagged::!=G,@x21),
  ! => @method(tagged::!,@x22),
  | => @method(tagged::|,@x23),
  >> => @method(tagged::>>,@x24),
  - => @method(tagged::-,@x25),
  ^ => @method(tagged::^,@x26),
  _inspect => @method(tagged::_inspect,@x27),
  clone => @method(tagged::clone,@x3)  )

  tort_string_new_cstr("cstring") => "cstring"
  tort_h_mtable(tort_string_new_cstr("cstring")) => @map( 
  __printfsv => @method(string::__printfsv,@x28),
  __write => @method(string::__write,@x29),
  _dlopen => @method(string::_dlopen,@x30),
  _inspect => @method(string::_inspect,@x31),
  get => @method(string::get,@x32),
  set => @method(string::set,@x33)  )

  tort__s(new) => new
  tort_h_mtable(tort__s(new)) => @map( 
  _inspect => @method(symbol::_inspect,@x34),
  _version_change => @method(symbol::_version_change,@x35),
  mtable_method_map => @method(symbol::mtable_method_map,@x36),
  name => @method(symbol::name,@x37),
  version => @method(symbol::version,@x38),
  clone => @method(symbol::clone,@x3)  )

  tort_object_make() => @object(@x39)
  tort_h_mtable(tort_object_make()) => @map( 
  __debugger => @method(object::__debugger,@x40),
  __message => @method(object::__message,@x41),
  __printfs => @method(object::__printfs,@x42),
  __printfsv => @method(object::__printfsv,@x43),
  __register_finalizer => @method(object::__register_finalizer,@x44),
  _alloc_size => @method(object::_alloc_size,@x45),
  _inspect => @method(object::_inspect,@x46),
  _method_not_found => @method(object::_method_not_found,@x47),
  _mtable => @method(object::_mtable,@x48),
  _name => @method(object::_name,@x49),
  _printfv => @method(object::_printfv,@x50),
  clone => @method(object::clone,@x51),
  eq? => @method(object::eq?,@x52),
  identity => @method(object::identity,@x3),
  not => @method(object::not,@x53),
  __finalize => @method(object::__finalize,@x3)  )

  _tort => @tort
  tort_h_mtable(_tort) => @map( 
    )

  tort_(root) => @map( 
  nil => nil,
  true => true,
  false => false,
  mtable => @map( 
  boolean => @map( 
  _inspect => @method(boolean::_inspect,@x4),
  clone => @method(boolean::clone,@x3)  ),
  eos => @map( 
    ),
  io => @map( 
  __finalize => @method(io::__finalize,@x54),
  __write => @method(io::__write,@x55),
  _write => @method(io::_write,@x56),
  close => @method(io::close,@x57),
  eof => @method(io::eof,@x58),
  error => @method(io::error,@x59),
  flush => @method(io::flush,@x60),
  open => @method(io::open,@x61),
  popen => @method(io::popen,@x62),
  read => @method(io::read,@x63)  ),
  map => @map( 
  _inspect => @method(map::_inspect,@x64),
  _load_symtab => @method(map::_load_symtab,@x65),
  add => @method(map::add,@x66),
  clone => @method(map::clone,@x67),
  delete => @method(map::delete,@x68),
  get => @method(map::get,@x69),
  get_entry => @method(map::get_entry,@x70),
  get_entry_by_value => @method(map::get_entry_by_value,@x71),
  get_entry_cstr => @method(map::get_entry_cstr,@x72),
  get_entry_string => @method(map::get_entry_string,@x73),
  get_key => @method(map::get_key,@x74),
  get_string => @method(map::get_string,@x75),
  initialize => @method(map::initialize,@x76),
  set => @method(map::set,@x77),
  _run_initializers => @method(map::_run_initializers,@x78),
  _load_methods => @method(map::_load_methods,@x79)  ),
  message => @map( 
  _inspect => @method(message::_inspect,@x80),
  backtrace => @method(message::backtrace,@x81)  ),
  method => @map( 
  _inspect => @method(method::_inspect,@x82)  ),
  mtable => @map( 
  lookup => @method(mtable::lookup,@x83),
  add_method => @method(mtable::add_method,@x84),
  allocate => @method(mtable::allocate,@x85),
  _allocate => @method(mtable::_allocate,@x86),
  _delegate_changed => @method(mtable::_delegate_changed,@x87),
  _method_changed => @method(mtable::_method_changed,@x88),
  delegate => @method(mtable::delegate,@x89),
  remove_method => @method(mtable::remove_method,@x90),
  set_delegate => @method(mtable::set_delegate,@x91)  ),
  nil => @map( 
  __printfsv => @method(nil::__printfsv,@x1),
  _inspect => @method(nil::_inspect,@x2),
  clone => @method(nil::clone,@x3)  ),
  object => @map( 
  __debugger => @method(object::__debugger,@x40),
  __message => @method(object::__message,@x41),
  __printfs => @method(object::__printfs,@x42),
  __printfsv => @method(object::__printfsv,@x43),
  __register_finalizer => @method(object::__register_finalizer,@x44),
  _alloc_size => @method(object::_alloc_size,@x45),
  _inspect => @method(object::_inspect,@x46),
  _method_not_found => @method(object::_method_not_found,@x47),
  _mtable => @method(object::_mtable,@x48),
  _name => @method(object::_name,@x49),
  _printfv => @method(object::_printfv,@x50),
  clone => @method(object::clone,@x51),
  eq? => @method(object::eq?,@x52),
  identity => @method(object::identity,@x3),
  not => @method(object::not,@x53),
  __finalize => @method(object::__finalize,@x3)  ),
  pair => @map( 
  _inspect => @method(pair::_inspect,@x92),
  first => @method(pair::first,@x93),
  second => @method(pair::second,@x94),
  set_first => @method(pair::set_first,@x95),
  set_second => @method(pair::set_second,@x96)  ),
  string => @map( 
  __printfsv => @method(string::__printfsv,@x28),
  __write => @method(string::__write,@x29),
  _dlopen => @method(string::_dlopen,@x30),
  _inspect => @method(string::_inspect,@x31),
  get => @method(string::get,@x32),
  set => @method(string::set,@x33)  ),
  symbol => @map( 
  _inspect => @method(symbol::_inspect,@x34),
  _version_change => @method(symbol::_version_change,@x35),
  mtable_method_map => @method(symbol::mtable_method_map,@x36),
  name => @method(symbol::name,@x37),
  version => @method(symbol::version,@x38),
  clone => @method(symbol::clone,@x3)  ),
  tagged => @map( 
  + => @method(tagged::+,@x6),
  & => @method(tagged::&,@x7),
  / => @method(tagged::/,@x8),
  == => @method(tagged::==,@x9),
  >= => @method(tagged::>=,@x10),
  > => @method(tagged::>,@x11),
  ~ => @method(tagged::~,@x12),
  && => @method(tagged::&&,@x13),
  <= => @method(tagged::<=,@x14),
  || => @method(tagged::||,@x15),
  << => @method(tagged::<<,@x16),
  < => @method(tagged::<,@x17),
  % => @method(tagged::%,@x18),
  * => @method(tagged::*,@x19),
  != => @method(tagged::!=,@x20),
  !=G => @method(tagged::!=G,@x21),
  ! => @method(tagged::!,@x22),
  | => @method(tagged::|,@x23),
  >> => @method(tagged::>>,@x24),
  - => @method(tagged::-,@x25),
  ^ => @method(tagged::^,@x26),
  _inspect => @method(tagged::_inspect,@x27),
  clone => @method(tagged::clone,@x3)  ),
  vector => @map( 
  _inspect => @method(vector::_inspect,@x97),
  add => @method(vector::add,@x98),
  each => @method(vector::each,@x99),
  get => @method(vector::get,@x100),
  map => @method(vector::map,@x101),
  set => @method(vector::set,@x102)  ),
  vector_base => @map( 
  _add => @method(vector_base::_add,@x103),
  _append => @method(vector_base::_append,@x104),
  _data => @method(vector_base::_data,@x105),
  _delete_n => @method(vector_base::_delete_n,@x106),
  _initialize => @method(vector_base::_initialize,@x107),
  _ref => @method(vector_base::_ref,@x108),
  _resize => @method(vector_base::_resize,@x109),
  alloc_size => @method(vector_base::alloc_size,@x110),
  append => @method(vector_base::append,@x111),
  clone => @method(vector_base::clone,@x112),
  element_size => @method(vector_base::element_size,@x113),
  size => @method(vector_base::size,@x114)  )  ),
  stdin => nil,
  stdout => nil,
  stderr => nil,
  core_symtab => @map( 
  _main => 4294970160,
  4294970160 => _main,
  start => 4294970096,
  4294970096 => start  )  )
  tort_h_mtable(tort_(root)) => @map( 
  _inspect => @method(map::_inspect,@x64),
  _load_symtab => @method(map::_load_symtab,@x65),
  add => @method(map::add,@x66),
  clone => @method(map::clone,@x67),
  delete => @method(map::delete,@x68),
  get => @method(map::get,@x69),
  get_entry => @method(map::get_entry,@x70),
  get_entry_by_value => @method(map::get_entry_by_value,@x71),
  get_entry_cstr => @method(map::get_entry_cstr,@x72),
  get_entry_string => @method(map::get_entry_string,@x73),
  get_key => @method(map::get_key,@x74),
  get_string => @method(map::get_string,@x75),
  initialize => @method(map::initialize,@x76),
  set => @method(map::set,@x77),
  _run_initializers => @method(map::_run_initializers,@x78),
  _load_methods => @method(map::_load_methods,@x79)  )

DONE
