
  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x1""
  (eof o) => 1
  (size v) => 0
  (alloc_size v) => 64


  o => @object @x2""
  (eof o) => 1
