
  _mt_map => !map { initialize => !method initialize @x1, get => !method get @x2, get_key => !method get_key @x3, set => !method set @x4, delete => !method delete @x5, clone => !method clone @x6, size => !method size @x7, _inspect => !method _inspect @x8, lisp_write => !method lisp_write @x9 }o => !map {  }
(size o) => 0
o => !map { 1 => 2 }
(size o) => 1
o => !map { 1 => 3 }
(size o) => 1
o => !map { 1 => 3, 3 => 4 }
(size o) => 2
o => !map { 3 => 4 }
(size o) => 1

DONE
