Some object ==> ( @message( __message, @io(@x1), @method(__message,@x2), @map( 
  __debugger => @method(__debugger,@x3),
  __message => @method(__message,@x2),
  __register_finalizer => @method(__register_finalizer,@x4),
  _alloc_size => @method(_alloc_size,@x5),
  _inspect => @method(_inspect,@x6),
  _method_not_found => @method(_method_not_found,@x7),
  _mtable => @method(_mtable,@x8),
  _name => @method(_name,@x9),
  clone => @method(clone,@x10),
  identity => @method(identity,@x11),
  __finalize => @method(__finalize,@x11)  )) ) <== is in here!

DONE
