(let ((v ('new <value> 1))
      (l #f)
      (sym (make-symbol '())))
  (write v)(newline)
  (write ('value v))(newline)
  (set! l ('value_locative v))
  (write l)(newline)
  (write ('value l))(newline)
  ('value= l 'changed-by-locative-value=)
  (write v)(newline)
  (write ('value v))(newline)
  )
